### ISSUE TITLE
Error! Bad return status for module build on kernel: 5.6.2-arch1-1-macbook (x86_64)

### ISSUE THREAD

**Issue by spikopath** [aur-packages/bcwc-pcie-git#4]
When building the package against the linux-macbook kernel I get this error:

`(2/2) Install DKMS modules
==> dkms install bcwc-pcie/r242.ea832ac -k 5.6.2-arch1-1-macbook
Error! Bad return status for module build on kernel: 5.6.2-arch1-1-macbook (x86_64)
Consult /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/make.log for more information.`

Output of the make.log:

`DKMS make.log for bcwc-pcie-r242.ea832ac for kernel 5.6.2-arch1-1-macbook (x86_64)
Sun 12 Apr 21:03:20 BST 2020
make: Entering directory '/usr/lib/modules/5.6.2-arch1-1-macbook/build'
  AR      /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/built-in.a
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_ddr.o
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_hw.o
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_drv.o
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_ringbuf.o
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_isp.o
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_v4l2.o
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_buffer.o
  CC [M]  /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_debugfs.o
/var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_drv.c: In function ‘fthd_pci_reserve_mem’:
/var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_drv.c:73:20: error: implicit declaration of function ‘ioremap_nocache’; did you mean ‘ioremap_cache’? [-Werror=implicit-function-declaration]
   73 |  dev_priv->s2_io = ioremap_nocache(start, len);
      |                    ^~~~~~~~~~~~~~~
      |                    ioremap_cache
/var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_drv.c:73:18: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   73 |  dev_priv->s2_io = ioremap_nocache(start, len);
      |                  ^
/var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_drv.c:79:19: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   79 |  dev_priv->s2_mem = ioremap_nocache(start, len);
      |                   ^
/var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_drv.c:85:19: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   85 |  dev_priv->isp_io = ioremap_nocache(start, len);
      |                   ^
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:267: /var/lib/dkms/bcwc-pcie/r242.ea832ac/build/fthd_drv.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1683: /var/lib/dkms/bcwc-pcie/r242.ea832ac/build] Error 2
make: Leaving directory '/usr/lib/modules/5.6.2-arch1-1-macbook/build'
`

It had worked previously with previous linux-macbook kernels.

If you require more information let me know.

Many thanks

**Comment by spikopath** [comment]
Partial resolution in the below thread:

`https://github.com/patjak/bcwc_pcie/wiki/Get-Started#get-started-on-arch`

When compiling the code there will be errors compiling the fthd_drv.c file, follow this solution:

`https://github.com/patjak/bcwc_pcie/issues/205`
